### ISSUE TITLE
James

### ISSUE THREAD

**Issue by dbeezt** [jmsnll/jmsnll.github.io#1]
Can you message Ee Ling (+44 7700 000000) and tell her to verify my number on WeChat please? I'm in China and the great firewall blocks any other communication method I've thought of. Thanks bro.

**Comment by jmsnll** [comment]
Thanks for opening your first issue! I've messaged her

**Comment by dbeezt** [comment]
Awesome. Hopefully she checks her phone. Will keep you posted. Thanks again.

**Comment by jmsnll** [comment]
Should be sorted now?

**Comment by dbeezt** [comment]
Could you forward these please? The QR code expires: ![image](https://github.com/jmsnll/jmsnll.github.io/assets/10518422/eefb46a9-8ee9-4797-99c2-aea1c8588db0)

METHOD TWO ![image](https://github.com/jmsnll/jmsnll.github.io/assets/10518422/7e272f87-bc71-438c-888f-3b03aadc296a)![image](https://github.com/jmsnll/jmsnll.github.io/assets/10518422/9280ae65-ecbb-4578-907c-bd58bf19b3ad)

Thanks again - I can receive texts etc but not send.

**Comment by jmsnll** [comment]
Sent

**Comment by jmsnll** [comment]
Should be verified now?

**Comment by dbeezt** [comment]
Sorted. Thanks a mil. Issue closed
